# Generated by Django 5.0.6 on 2024-10-18 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='machine',
        ),
        migrations.AddField(
            model_name='team',
            name='machine_id',
            field=models.CharField(default='default_machine_id', max_length=255, unique=True),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Machine',
        ),
    ]
