# Generated by Django 5.0.6 on 2024-10-19 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_notification_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='interest_group',
            field=models.CharField(default='default', max_length=255),
            preserve_default=False,
        ),
    ]
