# Generated by Django 5.0.6 on 2024-10-19 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_agv_power_consumption_agv_power_consumption_oon_and_more'),
        ('main', '0004_team_interest_group'),
    ]

    operations = [
    ]
