# Generated by Django 5.0.6 on 2024-10-25 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0006_task"),
    ]

    operations = [
        migrations.CreateModel(
            name="KPI",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField()),
                ("kpi_value", models.FloatField()),
                ("status", models.BooleanField()),
                ("kpi_name", models.CharField(max_length=255)),
            ],
        ),
    ]
