# Generated by Django 5.0.6 on 2024-10-25 22:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0010_alter_kpi_timestamp"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="kpi",
            unique_together=set(),
        ),
    ]
