# Generated by Django 5.0.6 on 2024-10-25 22:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0013_alter_kpi_unique_together"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="kpi",
            unique_together={("timestamp", "kpi_name")},
        ),
    ]
